### ISSUE TITLE
Offset not working

### ISSUE THREAD

**Issue by thomarse-ef** [risacher/sunwait#47]
Offset doesn't allow me to schedule things for _before_ a twilight event: `sunwait list sunset offset -00:30:00 51.48523N 2.56268W` produces `21:56`, as does `sunwait list sunset offset +00:30:00 51.48523N 2.56268W` and `sunwait list sunset offset 00:30:00 51.48523N 2.56268W`. FYI sunset at this location today is 21:26. Am I doing something wrong or is this a bug?

**Comment by davidsanner** [comment]
I'm seeing another issue with offset.
In a 'wait' usage, if a negative offset pushes the wait over an hour past midnight it returns before it should (immediately) 

> example:  sun sets @ 8:30pm and run at 4pm.
>  works / waits:   sunwait wait daylight offset -3:00  set
>   doesn't wait:   sunwait wait daylight offset -5:00 set

2nd example has the wait going over an hour into the next day so fails, returns immediately.

**Comment by thomarse-ef** [comment]
I just tried this on a fresh install, issue seems to be resolved. Not sure what happened there :)
